[package]
name = "splang"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
clap = { version = "4.5.4", features = ["cargo", "unicode", "env"] }
color-eyre = "0.6.3"
thiserror = "1.0.60"

[dev-dependencies]
assert_cmd = "2.0.14"
pretty_assertions = "1.4.0"
